config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :issues
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  post 'portfolios/image_upload' => 'portfolios#image_upload'
  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
end

app/views/layouts/modal/_contact.html.erb
<div id="contact" class="modal">
  <div class="modal-content">
    <div class="container">
      
      <%= link_to profiles_path, class: "contact-text" do %>
      Profile
        <span class="float-right light-blue lighten-1">
          link
        </span>
      <% end %>
      <p class="contact-title">Github </p>
      <a href="https://github.com/iceCreamParlor" class="contact-text">
        iceCreamParlor 
        <span class="float-right light-blue lighten-1">
          link
        </span>
      </a>
      <p class="contact-title">Email</p>
      <a class="contact-text">heejjeeh@gmail.com </a>
    </div>
  </div>
</div>

app/views/layouts/modal/_login.html.erb
<div id="login" class="modal">
  <div class="modal-content">
    <div class="row">
      <div class="col s12 m12 l12"></div>
      <div class="col s12 m12 l12">
        <h2 style="color: white;">Login</h2>
    
        <%= form_for(:user, :url => session_path(:user), :html => {:id => "loginForm"}) do |f| %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>
    
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "current-password" %>
          </div>

          </div>
          <div class="col s6 m6 l6" style="margin-top: 20px;">
            <div class="actions">
              <button id="loginButton" type="button" class= "btn-large waves-effect waves-light">
                  <i class="large material-icons">fingerprint</i>
              </button>
            </div>
          </div>
          
        <% end %>
      
    </div>
  </div>
</div>
<script>
  document.getElementById('loginButton').addEventListener('click', function(){
    document.getElementById('loginForm').submit();
  })
</script>