config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :issues
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  post 'portfolios/image_upload' => 'portfolios#image_upload'
  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/controllers/issues_controller.rb
class IssuesController < InheritedResources::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action :disable_carousel

  def index
    @issues = Issue.all.order(created_at: :desc)
  end

  
  def show
  end

  # GET /portfolios/new
  def new
    @issue = Issue.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_path, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def issue_params
      params.require(:issue).permit(:title, :content)
    end
    def set_issue
      @issue = Issue.find(params[:id])
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, id: "form", local: true) do |form| %>
  <div class="container">
    <% if issue.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

        <ul>
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="input-field col s12">
      <div class="editor" id="editor"></div>
    </div>
    <%= form.text_field :content, style: "visibility: hidden;" %>

    <div class="actions" style="float: right; margin-bottom: 100px;">
      <button class="waves-effect waves-light btn" id="submitButton">POST</button>
    </div>
  </div>
<% end %>

<script src="/js/editor/materialize.js"></script>

<script type="text/javascript">
document.addEventListener('turbolinks:load', function(){
  if(checkCurrentPage('issues-new') || checkCurrentPage('issues-edit')){
      var toolbar = [
        ['style', ['style', 'bold', 'italic', 'underline', 'strikethrough', 'clear']],
        ['fonts', ['fontsize', 'fontname']],
        ['color', ['color']],
        ['undo', ['undo', 'redo', 'help']],
        ['ckMedia', ['ckImageUploader', 'ckVideoEmbeeder']],
        ['misc', ['link', 'picture', 'table', 'hr', 'codeview', 'fullscreen']],
        ['para', ['ul', 'ol', 'paragraph', 'leftButton', 'centerButton', 'rightButton', 'justifyButton', 'outdentButton', 'indentButton']],
        ['height', ['lineheight']],
    ];

    $('.editor').summernote({
        toolbar: toolbar,
        height: 1000,
        minHeight: 100,
        defaultBackColor: '#fff',
        image: [
          ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
          ['float', ['floatLeft', 'floatRight', 'floatNone']],
          ['remove', ['removeMedia']]
        ],
        onImageUpload: function (files) {
          var $files = $(files);
          var $this = $(this);
          console.log($this)
          $files.each(function () {
            var file = this;
            
            var data = new FormData();
            data.append("file", file);

            $.ajax({
              data: data,
              type: "POST",
              url: "/portfolios/image_upload/",
              cache: false,
              contentType: false,
              processData: false,
              success: function (url) {
                var image = $('<img class="responsive-image" />').attr('src', '/uploads/' + url.file_name);
                $('#editor').summernote("insertNode", image[0]);
                  
              },
              error: function (xhr, ajaxOptions, thrownError) {
                  if (xhr.responseText) {
                      toastr.error(xhr.responseText, 'Inconceivable!')
                  } else {
                      console.error("<div>Http status: " + xhr.status + " " + xhr.statusText + "</div>" + "<div>ajaxOptions: " + ajaxOptions + "</div>"
                          + "<div>thrownError: " + thrownError + "</div>");
                  }
              }
            });
          });
        }
    });

    // button 들의 action 을 없앤다. (이걸 지우면, 버튼을 눌렀을 때 form 이 submit 되는 현상 발생)
    var buttons = document.querySelectorAll('button'),
    fn      = function(e) { e.preventDefault() };

    for ( var i = buttons.length; i--; ) {
      buttons[i].addEventListener('click', fn, false);
    }

    if(<%= action_name == "edit" %>){
      let content = document.getElementsByClassName('note-editable')[0];
      content.innerHTML = document.getElementById('issue_content').value
    }

    document.getElementById('submitButton').addEventListener('click', function(e){
      e.preventDefault();
      let form = document.getElementById('form');
      let content = document.getElementsByClassName('note-editable')[0]
      let totalWidth = content.offsetWidth;
      
      let imgs = content.getElementsByTagName('img');
      
      for(var i = 0 ; i < imgs.length ; i++){
        img = imgs[i];
        
        if(img.style.height.indexOf('px') != -1 || img.style.width.indexOf('px') != -1 ){
          // 새로 추가된 사진일 경우에만 px => % 로 크기 조정한다.
          let imgHeight = parseFloat(imgs[i].style.height.replace('px', ''));   
          let imgWidth = parseFloat(imgs[i].style.width.replace('px', ''));
          let imgRatio = imgHeight / imgWidth;
          let withEditorRatio = imgWidth / totalWidth * 100;
          img.style.width = withEditorRatio + '%';
          img.style.height = withEditorRatio * imgRatio + '%';
        }
      }
      
      document.getElementById('issue_content').value = content.innerHTML;
      let title_value = document.getElementById('issue_title').value;
      let content_value = document.getElementById('issue_content').value;

      if( content_value == "" || title_value == "" ){
        alertToast('항목을 모두 입력해 주세요.');
      } else {
        form.submit();
      }
      
    })
  }
  
});
</script> 

app/views/issues/edit.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/index.html.erb
<%= content_tag "div", id:"issues-index", data: { issues: @issues.to_json} do%>
<div class="container">
  <h4 class="white-text">Issues</h4>
  <% if user_signed_in? && check_authority %>
    <%= link_to new_issue_path do %>
      <button type="button">New Issue</button>
    <% end %>
  <% end %>
  <div class="input-field col s6 white-text" style="margin: 1.5em; ">
    <i class="material-icons prefix">search</i>
    <input id="searchIssue" onkeyup="searchIssue()">
  </div>



  <div class="masonry">
    <% @issues.each do |issue| %>
    
    <div class="item hoverable non-scrollbar" id="card-<%= issue.id %>" style="overflow: scroll;">
        <%= link_to issue_path(issue) do %>
        <p style="color: #1D262A; font-size: 20px; font-weight: 800 !important;"><%= issue.title %></p>
        <span class="black-text">
          <%= issue.content.html_safe %>
        </span>
        <% end %>
    </div>
    
    <% end %>

  </div>

</div>
<% end %>

<script>
  var issues;
  let cardBgColors = ["#FDF4A7", "#BBF2FD", "#F7C9C8", "#EEEEEE"];
  let colorCount = cardBgColors.length;


  document.addEventListener('turbolinks:load', function(){
    if(checkCurrentPage('issues-index')){
      issues = JSON.parse(document.getElementById('issues-index').dataset.issues);
      cards = document.getElementsByClassName('item hoverable');
      
      for(var i = 0 ; i < cards.length ; i++) {
        colorIndex = Math.floor(Math.random() * colorCount);
        cards[i].style.maxHeight = 200 + Math.random() * 300 + 'px';
        cards[i].style.backgroundColor = cardBgColors[colorIndex];
      }
      
    }

  })
  
  function searchIssue(){

    let inputField = document.getElementById('searchIssue').value.toLowerCase();

    for(var i = 0 ; i < issues.length ; i++){
      $(('#card-' + issues[i].id)).show();

      if( issues[i].title.toLowerCase().indexOf(inputField) == -1 ){
        $(('#card-' + issues[i].id)).hide();

      }
    }
  }
</script>

<style>

.masonry { /* Masonry container */
  -webkit-column-count: 4;
  -moz-column-count:4;
  column-count: 4;
  -webkit-column-gap: 1em;
  -moz-column-gap: 1em;
  column-gap: 1em;
  margin: 1.5em;
  padding: 0;
  -moz-column-gap: 1.5em;
  -webkit-column-gap: 1.5em;
  column-gap: 1.5em;
  font-size: .85em;
}
.item {
    display: inline-block;
    background: #fff;
    padding: 1em;
    margin: 0 0 1.5em;
    width: 100%;
	-webkit-transition:1s ease all;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-shadow: 2px 2px 4px 0 #ccc;
}
.item img{max-width:100%;}

@media only screen and (max-width: 320px) {
    .masonry {
        -moz-column-count: 1;
        -webkit-column-count: 1;
        column-count: 1;
    }
}

@media only screen and (min-width: 321px) and (max-width: 768px){
    .masonry {
        -moz-column-count: 1;
        -webkit-column-count: 1;
        column-count: 1;
    }
}
@media only screen and (min-width: 769px) and (max-width: 1200px){
    .masonry {
        -moz-column-count: 2;
        -webkit-column-count: 2;
        column-count: 2;
    }
}
@media only screen and (min-width: 1201px) {
    .masonry {
        -moz-column-count: 3;
        -webkit-column-count: 3;
        column-count: 3;
    }
}
</style>

app/views/issues/new.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<div class="container">
  <div class="issue-setting" style="float: right;">
  <%= link_to issues_path, class: "float-btn btn-floating green fixed", style: "right: 50px; bottom: 50px;" do %>
    <i class="material-icons">arrow_back</i>
  <% end %>
  <% if user_signed_in? %>
    <% if check_authority %>
      <%= link_to edit_issue_path(@issue), data: {confirm: "수정하시겠습니까 ?"}, class: "float-btn btn-floating blue fixed", style: "right: 150px; bottom: 50px;" do %>
        <i class="material-icons">edit</i>
      <% end %>
    <% else %>
      <a class= "float-btn btn-floating blue fixed" onclick="alertToast('수정 권한이 없습니다.')">
        <i class="material-icons">edit</i>
      </a>
    <% end %>
  
    <% if check_authority %>
      <%= link_to issue_path(@issue), method: :delete, data: {confirm: "정말 삭제하시겠습니까?"}, class: "float-btn btn-floating red fixed", style: "right: 100px; bottom: 50px;" do %>
        <i class="material-icons">delete_forever</i>
      <% end %>
    <% else %>
      <a class= "float-btn btn-floating red" onclick="alertToast('삭제 권한이 없습니다.')">
        <i class="material-icons">delete_forever</i>
      </a>
    <% end %>
  <% end %>
  </div>


  <h4 style="margin-top:40px;"><%= @issue.title %></h4>
  <div class="issue-content">
    <%= @issue.content.html_safe %>
  </div>
</div>

<style>
  h4{
    color: white
  }
  div{
    color: white
  }
  .issue-content {
    margin-top: 80px;
  }
</style>