config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :issues
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  post 'portfolios/image_upload' => 'portfolios#image_upload'
  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_and_belongs_to_many :hashtags
  accepts_nested_attributes_for :hashtags

  before_destroy :check_hashtag_valid

  def check_hashtag_valid
    puts "before destroy!"
    hashtags = self.hashtags
    
    hashtags.each do |hashtag|
      puts hashtag.title
      if hashtag.portfolios.count == 1
        hashtag.delete
      end
    end
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :disable_carousel
  skip_before_action :verify_authenticity_token, only: [:image_upload]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all.order(created_at: :desc)
    @hashtags = Hashtag.all.order(created_at: :desc)
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
    5.times { @portfolio.hashtags.new }
    @disable_carousel = true
  end

  # GET /portfolios/1/edit
  def edit
    @disable_carousel = true
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    # 해시태그가 기존에 존재하면 그대로 내버려두고, 없으면 해시태그를 새로 생성
    5.times do |x|
      tag = hashtag_params[:hashtags_attributes]["#{x}"]["title"]
      if tag != ""
        a = Hashtag.find_or_create_by(title: tag)
        @portfolio.hashtags << a
      end
    end

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to '/', notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to '/', notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image_upload
    image_binary = params[:file]
    file_name = "#{SecureRandom.urlsafe_base64}.png"

    File.open(Rails.root.join('public','uploads', file_name), 'wb') do |f|
      if f.write(image_binary.read)
        render :json => {
          file_name: file_name
        } 
      end 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title, :content, :thumbnail)
    end
    def hashtag_params
      params.require(:portfolio).permit(hashtags_attributes: [:title])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, id: "form", local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container" style="margin-top: 20px;">
    <div class="row">
      <div class="col s12 m5 l5">
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col s12 m5 l5">
        <div class="field">
          <ul>
            <%= form.fields_for :hashtags do |hashtag| %>
            <li>
              <%= hashtag.label :title, '태그' %>
              <%= hashtag.text_field :title %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="input-field col s12">
        <p class="white-text">* 모바일에서만 100% width로 보이고 싶은 이미지에는 class="responsive-image" 추가</p>
        <div class="editor" id="editor"></div>
    </div>
    <%= form.text_field :content, style: "visibility: hidden;" %>
    
    <!-- Cropper -->
    <%= form.text_field :thumbnail, style: "visibility: hidden;" %>
    <p>
    <!-- Below are a series of inputs which allow file selection and interaction with the cropper api -->
        <input type="file" id="fileInput" accept="image/*" />
        <input type="button" id="btnCrop" value="Crop" />
        <input type="button" id="btnRestore" value="Restore" />
    </p>
    <div>
      <canvas id="canvas">
        Your browser does not support the HTML5 canvas element.
      </canvas>
    </div>		
    
    <div id="result"></div>
    
    <div class="actions" style="float: right; margin-bottom: 100px;">
      <button class="waves-effect waves-light btn" id="submitButton">POST</button>
    </div>
  </div>
  <!-- Cropper -->
  
<% end %>

<script src="/js/editor/materialize.js"></script>

<script type="text/javascript">
document.addEventListener('turbolinks:load', function(){

  if(checkCurrentPage('portfolios-new') || checkCurrentPage('portfolios-edit')){
    var toolbar = [
      ['style', ['style', 'bold', 'italic', 'underline', 'strikethrough', 'clear']],
      ['fonts', ['fontsize', 'fontname']],
      ['color', ['color']],
      ['undo', ['undo', 'redo', 'help']],
      ['ckMedia', ['ckImageUploader', 'ckVideoEmbeeder']],
      ['misc', ['link', 'picture', 'table', 'hr', 'codeview', 'fullscreen']],
      ['para', ['ul', 'ol', 'paragraph', 'leftButton', 'centerButton', 'rightButton', 'justifyButton', 'outdentButton', 'indentButton']],
      ['height', ['lineheight']],
    ];

    $('.editor').summernote({
        toolbar: toolbar,
        height: 1000,
        minHeight: 100,
        defaultBackColor: '#fff',
        image: [
          ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
          ['float', ['floatLeft', 'floatRight', 'floatNone']],
          ['remove', ['removeMedia']]
        ],
        
        onImageUpload: function (files) {
          var $files = $(files);
          var $this = $(this);
          console.log($this)
          $files.each(function () {
            var file = this;
            
            var data = new FormData();
            data.append("file", file);

            $.ajax({
              data: data,
              type: "POST",
              url: "/portfolios/image_upload/",
              cache: false,
              contentType: false,
              processData: false,
              success: function (url) {
                var image = $('<img class="responsive-image" />').attr('src', '/uploads/' + url.file_name);
                $('#editor').summernote("insertNode", image[0]);
                  
              },
              error: function (xhr, ajaxOptions, thrownError) {
                  if (xhr.responseText) {
                      toastr.error(xhr.responseText, 'Inconceivable!')
                  } else {
                      console.error("<div>Http status: " + xhr.status + " " + xhr.statusText + "</div>" + "<div>ajaxOptions: " + ajaxOptions + "</div>"
                          + "<div>thrownError: " + thrownError + "</div>");
                  }
              }
            });
          });
        }
        
    });

    // button 들의 action 을 없앤다. (이걸 지우면, 버튼을 눌렀을 때 form 이 submit 되는 현상 발생)
    var buttons = document.querySelectorAll('button'),
    fn      = function(e) { e.preventDefault() };

    for ( var i = buttons.length; i--; ) {
      buttons[i].addEventListener('click', fn, false);
    }

    if(<%= action_name == "edit" %>){
      let content = document.getElementsByClassName('note-editable')[0];
      content.innerHTML = document.getElementById('portfolio_content').value
    }


    var canvas  = $("#canvas"),
      context = canvas.get(0).getContext("2d"),
      $result = $('#result');

    $('#fileInput').on( 'change', function(){
        if (this.files && this.files[0]) {
          if ( this.files[0].type.match(/^image\//) ) {
            var reader = new FileReader();
            reader.onload = function(evt) {
              var img = new Image();
              img.onload = function() {
                context.canvas.height = img.height;
                context.canvas.width  = img.width;
                context.drawImage(img, 0, 0);
                var cropper = canvas.cropper({
                  aspectRatio: 16 / 9
                });
                $('#btnCrop').click(function() {
                    // Get a string base 64 data url
                    console.log(canvas)
                    var croppedImageDataURL = canvas.cropper('getCroppedCanvas').toBlob(function (blob) {
                      var data = new FormData();

                      data.append('file', blob);

                      $.ajax({
                        data: data,
                        type: "POST",
                        url: "/portfolios/image_upload/",
                        cache: false,
                        contentType: false,
                        processData: false,
                        success: function (response) {
                          console.log(response)     
                          document.getElementById('portfolio_thumbnail').value = '/uploads/' + response.file_name
                          alert("Image Upload Success!")
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            if (xhr.responseText) {
                                toastr.error(xhr.responseText, 'Inconceivable!')
                            } else {
                                console.error("<div>Http status: " + xhr.status + " " + xhr.statusText + "</div>" + "<div>ajaxOptions: " + ajaxOptions + "</div>"
                                    + "<div>thrownError: " + thrownError + "</div>");
                            }
                        }
                      });


                    });
            
                    
                });
                $('#btnRestore').click(function() {
                  canvas.cropper('reset');
                  $result.empty();
                });
              };
              img.src = evt.target.result;
            };
            reader.readAsDataURL(this.files[0]);
          }
          else {
            alert("Invalid file type! Please select an image file.");
          }
        }
        else {
          alert('No file(s) selected.');
        }
    });
  }
  
  document.getElementById('submitButton').addEventListener('click', function(e){
    e.preventDefault();
    let form = document.getElementById('form');
    let content = document.getElementsByClassName('note-editable')[0]
    let totalWidth = content.offsetWidth;
    
    let imgs = content.getElementsByTagName('img');
    
    for(var i = 0 ; i < imgs.length ; i++){
      img = imgs[i];
      
      if(img.style.height.indexOf('px') != -1 || img.style.width.indexOf('px') != -1 ){
        // 새로 추가된 사진일 경우에만 px => % 로 크기 조정한다.
        let imgHeight = parseFloat(imgs[i].style.height.replace('px', ''));   
        let imgWidth = parseFloat(imgs[i].style.width.replace('px', ''));
        let imgRatio = imgHeight / imgWidth;
        let withEditorRatio = imgWidth / totalWidth * 100;
        img.style.width = withEditorRatio + '%';
        img.style.height = withEditorRatio * imgRatio + '%';
      }
    }
    
    document.getElementById('portfolio_content').value = content.innerHTML;
    let title_value = document.getElementById('portfolio_title').value;
    let content_value = document.getElementById('portfolio_content').value;
    let thumbnail_value = document.getElementById('portfolio_thumbnail').value;

    if( content_value == "" || thumbnail_value == "" || title_value == "" ){
      alertToast('항목을 모두 입력해 주세요.');
    } else {
      form.submit();
    }
    
  })

})

</script> 

app/views/portfolios/edit.html.erb
<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<%= content_tag "div", id:"portfolios-index", data: { portfolios: @portfolios.to_json} do%>
<div class="container">
  <h4 class="white-text">Portfolio</h4>
  <div class="row" style="margin-top: 20px;">
    <% @hashtags.each do |hashtag| %>
    <div class="col s4 m4 l2">
      <label>
        <input type="checkbox" class="filled-in" value="<%= hashtag.id %>" checked="checked" onchange="checkboxToggled(this)" />
        <span style="font-size: 13px;overflow:hidden;"><%= hashtag.title %></span>
      </label>
    </div>
    <% end %>
  </div>
  
    <% @portfolios.each_with_index do |portfolio, index| %>
    
    <% if index % 3 == 0 %>
    <div class="row">
    <% end %>

      <%= link_to portfolio_path(portfolio), data: { turbolinks: false } do %>
      <div class="col s12 m4 l4">
        
          <div class="card" id="portfolio-<%= portfolio.id %>">
            <div class="card-image">
              <img src="<%= portfolio.thumbnail %>" class="hoverable">
              <!-- <span class="card-title"><%= portfolio.title %></span> -->
              <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
            </div>
            <div class="card-content">
              <h4 class="black-text"><%= portfolio.title %></h4>
              <% portfolio.hashtags.each do |hashtag| %>
                <div class="chip" >
                  <%= hashtag.title %>
                </div>
              <% end %>
            </div>
          </div>
      </div>
      <% end %>

    <% if index % 3 == 2 %>
    </div>
    <% end %>
    <% end %>
  
</div>
<% end %>

<script>
  var portfolios;
  var portfolio_hashtags = [];
  document.addEventListener('turbolinks:load', function(){
    if(checkCurrentPage('portfolios-index')){
      
      portfolios = JSON.parse(document.getElementById('portfolios-index').dataset.portfolios);
      <% @portfolios.each do |portfolio| %>
        var tempHashtag = [];
        <% portfolio.hashtags.each do |hashtag| %>
        tempHashtag.push(<%= hashtag.id %>)
        <% end %>
        portfolio_hashtags.push(tempHashtag)
      <% end %>
    }
    
  })
  function checkboxToggled(e){
    let hashtagId = parseInt(e.value);
    let isChecked = e.getAttribute('checked');
    if (isChecked == 'checked') {
      e.setAttribute('checked', 'unchecked');
      isChecked = 'unchecked';
    } else {
      e.setAttribute('checked', 'checked');
      isChecked = 'checked';
    }
    portfolios.forEach(function(portfolio){
      portfolio['isShown'] = false;
    })
    
    let selected_hashtag_id = []

    $("input:checkbox").each(function(){
      if($(this).is(":checked")){
        selected_hashtag_id.push(parseInt($(this).val()));
      }
    })
    
    for(var i = 0 ; i < portfolio_hashtags.length ; i++){
      portfolio_hashtags[i].forEach(function(hashtag){
        
        if(selected_hashtag_id.indexOf(hashtag) != -1){
          portfolios[i]['isShown'] = true
        }  
      })
    }
    
    portfolios.forEach(function(portfolio){
      if(portfolio['isShown']){
        // console.log("block")
        document.getElementById('portfolio-'+portfolio.id).style.display="block";
      } else {
        // console.log('hidden')
        document.getElementById('portfolio-'+portfolio.id).style.display="none";
      }
    })

  }
</script>

app/views/portfolios/new.html.erb
<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<div class="container">
  
    <div class="portfolio-setting" style="float: right;">

      <%= link_to portfolios_path, class: "float-btn btn-floating green fixed", style: "right: 50px; bottom: 50px;" do %>
        <i class="material-icons">arrow_back</i>
      <% end %>
      <% if user_signed_in? %>
        <% if check_authority %>
          <%= link_to edit_portfolio_path(@portfolio.id), data: {confirm: "수정하시겠습니까 ?"}, class: "float-btn btn-floating blue fixed", style: "right: 150px; bottom: 50px;" do %>
            <i class="material-icons">edit</i>
          <% end %>
        <% else %>
          <a class= "float-btn btn-floating blue" onclick="alertToast('수정 권한이 없습니다.')">
            <i class="material-icons">edit</i>
          </a>
        <% end %>
      
        <% if check_authority %>
          <%= link_to portfolio_path(@portfolio.id), method: :delete, data: {confirm: "정말 삭제하시겠습니까?"}, class: "float-btn btn-floating red fixed", style: "right: 100px; bottom: 50px;" do %>
            <i class="material-icons">delete_forever</i>
          <% end %>
        <% else %>
          <a class= "float-btn btn-floating red" onclick="alertToast('삭제 권한이 없습니다.')">
            <i class="material-icons">delete_forever</i>
          </a>
        <% end %>
      <% end %>
    </div>
  

  <div class="card blue-grey darken-4">
    <div class="card-content white-text">
      <span class="card-title"><%= @portfolio.title %></span>
      <%= @portfolio.content.html_safe %>
    </div>
  </div>
</div>