config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :issues
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  post 'portfolios/image_upload' => 'portfolios#image_upload'
  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
end

app/views/layouts/_home_index_top_image.html.erb
<div class="nav-background">
  <!-- <img class="active" src="http://placehold.it/1400x600" alt="control room"> -->
</div>
<div class="nav-header valign-wrapper">
  <div class="center">
    <h1>Kim Heejae</h1>
    <div class="tagline">Web / Web App / iOS Developer</div>
  </div>
</div>
<!-- Fixed Masonry Filters -->
<div class="categories-wrapper">
  <div class="categories-container">
    <ul class="categories container">
      <li class="active">
        <%= link_to 'All', '#all', data: { turbolinks: false } %>
      </li>
      
      <% @hashtags.each_with_index do |hashtag, index| %>
        <!-- <li class="<% if hashtag.title=='rails' %>active category<%end%>"> -->
        <li>
          <%= link_to "#{ hashtag.title.humanize }", "##{ hashtag.title }", data: { turbolinks: false } %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<a href="javascript:void plusFriendChat()" id="plusfriend-chat-button">
  <img src="/images/question_small_yellow_pc_3X.png" style="width:100px";/>
</a>

<script>
  document.addEventListener('DOMContentLoaded',function(event){
    if(checkCurrentPage('home-index')){
      
      // if(document.getElementsByClassName('active category')[0]){
      //   document.getElementsByClassName('active category')[0].click()
      // }
      // array with texts to type in typewriter
      // var dataText = [ "Amsterdam.", "Full Service.", "Webdevelopment.", "Wij zijn Occhio!"];
      var dataText = [ "Web / Web App / iOS Developer", "Freelancer Developer"];

      // type one text in the typwriter
      // keeps calling itself until the text is finished
      function typeWriter(text, i, fnCallback) {
        // chekc if text isn't finished yet
        if (i < (text.length)) {
          // add next character to h1
        document.querySelector(".tagline").innerHTML = text.substring(0, i+1) +'<span aria-hidden="true"></span>';

          // wait for a while and call this function again for next character
          setTimeout(function() {
            typeWriter(text, i + 1, fnCallback)
          }, 100);
        }
        // text finished, call callback if there is a callback function
        else if (typeof fnCallback == 'function') {
          // call callback after timeout
          setTimeout(fnCallback, 700);
        }
      }
      // start a typewriter animation for a text in the dataText array
      function StartTextAnimation(i) {
        if (typeof dataText[i] == 'undefined'){
            setTimeout(function() {
              StartTextAnimation(0);
            }, 1000);
        } else {

          // check if dataText[i] exists
          if (i < dataText[i].length) {
            // text exists! start typewriter animation
          typeWriter(dataText[i], 0, function(){
            // after callback (and whole text has been animated), start next text
            StartTextAnimation(i + 1);
          });
          }

        }
        
      }
      // start the text animation
      StartTextAnimation(0);
    }
    
  });

</script>
<script type='text/javascript'>
  Kakao.init('1b4bd5f23c8d8d7ef5475537ddf8bd0d');
  function plusFriendChat() {
    Kakao.PlusFriend.chat({
      plusFriendId: '_lxmKBj' // 플러스친구 홈 URL에 명시된 id로 설정합니다.
    });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kim Heejae</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- Lato Font -->
    <link href='http://fonts.googleapis.com/css?family=Inconsolata|Nanum+Gothic|Lato:300,400,700' rel='stylesheet' type='text/css' />

    <!-- Stylesheet -->
    <link href="/css/gallery-dark-materialize.css" rel="stylesheet">

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Cropper -->
    <link href="/css/cropper/cropper.min.css" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css?family=Inconsolata|Nanum+Gothic" rel="stylesheet"> -->
    <script src="/js/cropper/cropper.min.js"></script>
    <script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>

  </head>
  <div id="wallpaper" style="position: absolute; width: 10000px; z-index: 499; height: 10000px; background-color:#2A373E"></div>
  <div id="preloader" style="position: fixed; left: 50%; top: 55%; margin-left: -15px; margin-top: -15px; z-index:500;">
    <div class="preloader-wrapper small active">
        <div class="spinner-layer">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
    <p class="white-text" style="font-size: 12px;">로딩중..</p>
  </div>

  <body class="blue-grey darken-4" <% if controller_name=="home" && action_name == "index" %>onscroll="homeIndexScrollDown()" <% end %>>
      
      <!-- Navbar and Header -->
      <nav class="nav-extended <% if @disable_carousel.nil? && controller_name != "sessions" %> nav-full-header <% end %> z-depth-0 blue-grey darken-3">
        
        <div style="min-height: 50px; line-height: 50px;" class="nav-wrapper container">
          <%= link_to '/', class: "brand-logo", style: "font-size: 20px;" ,data: { turbolinks: false }  do %>
            <span style="font-size: 18px;" class="adjusted-min-height">heej</span>
            <i class="material-icons adjusted-min-height">laptop_mac</i>
          <% end %>
          <!-- <a href="/" class="brand-logo"><i class="material-icons">camera</i>imheej</a> -->
          <a href="#" style="margin-left: 0px;" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons adjusted-min-height">menu</i></a>
          <ul class="right hide-on-med-and-down adjusted-min-height">
            <li class="no-vertical-margin">
              <%= link_to 'Home', '/', data: { turbolinks: false } %>
            </li>
            
            <li class="no-vertical-margin">
              <%= link_to 'Issues', issues_path, data: { turbolinks: false } %>
            </li>
            <li class="no-vertical-margin">
              <%= link_to 'Portfolio', portfolios_path, data: { turbolinks: false } %>
            </li>
            <li class="no-vertical-margin">
              <%= link_to 'Profile', profiles_path, data: { turbolinks: false } %>
            </li>
            <li class="no-vertical-margin">
              <%= link_to 'Contact', '#contact', class: 'modal-trigger' %>
            </li>
            <li class="no-vertical-margin">
            <% if user_signed_in? %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %> 
            <% else %>
              <%= link_to 'Login', '#login', class: 'modal-trigger' %>
            <% end %>
            </li class="no-vertical-margin">
            <% if user_signed_in? && check_authority %>
            <li class="no-vertical-margin">
              <a class='dropdown-trigger' href='#' data-target='feature-dropdown'>Post<i class="material-icons right">arrow_drop_down</i></a>
            </li>
            <% end %>
          </ul>
          <% if user_signed_in? && check_authority %>
          <!-- Dropdown Structure -->
          <ul id='feature-dropdown' class='dropdown-content'>
            <li><%= link_to 'Portfolio', new_portfolio_path %></li>
            <li><%= link_to 'Issues', new_issue_path %></li>
            <li><%= link_to 'Profile', new_profile_path %></li>
          </ul>
          <% end %>
        </div>
          <%= render 'layouts/home_index_top_image' if @disable_carousel.nil? && controller_name != "sessions" %>      
      </nav>
      
      <ul class="sidenav" id="nav-mobile">
        <li class="active">
          <%= link_to 'Home', '/', data: { turbolinks: false } %>
        </li>
        <li>
          <%= link_to 'Issues', issues_path, data: { turbolinks: false } %>
        </li>
        <li><%= link_to 'Portfolio', portfolios_path, data: { turbolinks: false } %></li>
        <li><%= link_to 'Profile', profiles_path, data: { turbolinks: false } %></li>
        <li>
          <%= link_to 'Contact', '#contact', class: 'modal-trigger' %>
        </li>
        
        <li>
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %> 
        <% else %>
          <%= link_to 'Login', '#login', class: 'modal-trigger' %>
        <% end %>
        </li>
        
        <% if user_signed_in? %>
        <li><%= link_to 'New Portfolio', new_portfolio_path %></li>
        <li><%= link_to 'New Issues', new_issue_path %></li>
        <% end %>
        
      </ul>
      <div data-page="<%= @page_name ||= "#{controller_name}-#{action_name}" %>" class="page">
        <%= yield %>

        <!-- MODALS !! -->
        <%= render 'layouts/modal/login', resource: User.new, resource_name: :user, devise_mapping: Devise.mappings[:user] %>
        <%= render 'layouts/modal/contact' %>
      </div>
    <!-- Core Javascript -->
    

    <script src="/js/imagesloaded.pkgd.min.js"></script>
    <script src="/js/masonry.pkgd.min.js"></script>
    <script src="/js/materialize.min.js"></script>
    <script src="/js/color-thief.min.js"></script>
    <script src="/js/galleryExpand.js"></script>
    <script src="/js/init.js"></script>

    <!-- SummerNote (Materializecss) -->
    <link href="/css/editor/materialSummernote.css" rel="stylesheet">
    <link href="/css/editor/codeMirror/codemirror.css" rel="stylesheet">
    <link href="/css/editor/codeMirror/monokai.css" rel="stylesheet">
    
    <script type="text/javascript" src="/js/editor/materialize.js"></script>
    <script type="text/javascript" src="/js/editor/zzz_ckMaterializeOverrides.js"></script>

    <script type="text/javascript" src="/js/editor/codeMirror/codemirror.js"></script>
    <script type="text/javascript" src="/js/editor/codeMirror/xml.js"></script>
    <script type="text/javascript" src="/js/editor/materialSummernote.js"></script>
    <script>
      <% if notice.present? %>
        alertToast("<%= notice %>");
      <% end %>

      var isModalShowing = false;
      var maxCount = 1;
      function homeIndexScrollDown(){
        if(!isModalShowing && maxCount > 0){
          maxCount -= 1;
          isModalShowing = !isModalShowing;
          Materialize.toast('하단의 사진을 클릭해 보세요.', 2000, 'blue', function(){isModalShowing = !isModalShowing})
        }
      }
    </script>
    <script>
      document.addEventListener('turbolinks:load', function(){
        
        document.getElementById('wallpaper').style.display="none"
        document.getElementById('preloader').style.display="none";
    
      })
    </script>

  </body>
</html>
    